app.version=${app.version}
app.update.url=https://github.com/rupphi/relatest-wcode
app.update.public-key=${app.update.public-key}
app.update.publisher=${app.update.publisher}
app.license.url=https://wcode.online
