import type { Language } from "../../i18n";
import { defaultPurchaseDialogCopy } from "./ZnackPurchaseCopy";

const ru = {
  header: { aria: "Znack Automation", title: "Защищённый контур Znack", description: "CryptoPro, синхронизация каталога и локальный жизненный цикл GTIN без передачи секретов в WebView.", badge: "Защищённый Java bridge" },
  tabs: { aria: "Разделы Znack", settings: "Настройки", products: "Товары", deleted: "Скрытые", purchases: "Покупки", logs: "Журнал" },
  settings: {
    loading: "Загрузка настроек Znack", loadError: "Не удалось загрузить настройки Znack", retryLoad: "Повторить загрузку настроек",
    saved: "Настройки Znack сохранены", saveError: "Не удалось сохранить настройки. Загрузите актуальные данные и повторите.", reloadCurrent: "Загрузить актуальные",
    certificatesError: "Не удалось найти сертификаты CryptoPro. Проверьте установку и повторите.", certificateSaved: "Сертификат проверен и сохранён", certificateTestError: "Проверка сертификата не выполнена. Найдите сертификаты заново и повторите.",
    omsConnection: "Соединение OMS", defaultDocument: "Документ по умолчанию", documentNumber: "Номер документа", documentDate: "Дата документа", datePlaceholder: "дд.мм.гггг",
    autoIntroduction: "Автоматический ввод в оборот", autoIntroductionHint: "Запускать только когда документы и metadata GTIN готовы.", invalid: "Заполните OMS-поля и оба поля документа либо оставьте оба пустыми.", saving: "Сохранение…", save: "Сохранить настройки Znack",
    signature: {
      verifiedTitle: "Подпись проверена", verifiedDetail: "Конфигурация готова для безопасных операций.", expiredTitle: "Сертификат истёк", expiredDetail: "Выберите и проверьте действующий сертификат.",
      notVerifiedTitle: "Подпись не проверена", notVerifiedDetail: "Найдите сертификат CryptoPro и подтвердите подпись.", unconfiguredTitle: "Сертификат не настроен", unconfiguredDetail: "Поиск выполняется локально, selector остаётся в Java.",
    },
    validUntil: "Действует до {date}", discoverAria: "Найти сертификаты CryptoPro", discovering: "Поиск…", discover: "Найти сертификаты", saveFirst: "Сначала сохраните изменения настроек.", discoveryFailed: "Поиск не выполнен.", none: "Доступные сертификаты не найдены.",
    inn: "ИНН", expired: "Срок действия истёк", noPrivateKey: "Закрытый ключ недоступен", ready: "Готов к проверке", testAria: "Проверить выбранный сертификат", testing: "Ожидание CryptoPro…", test: "Проверить сертификат",
    privacy: "Selector, thumbprint, executable paths и metadata сертификата не передаются в WebView.",
  },
  products: {
    synced: "Синхронизировано товаров: {count}", syncCancelled: "Синхронизация остановлена. Уже сохранённые локальные пакеты не откатываются.", syncRetryable: "Синхронизация не завершена. Проверьте соединение и повторите.", syncRejected: "Синхронизация отклонена. Проверьте сертификат и настройки Znack.", syncStatusError: "Не удалось получить статус синхронизации Znack.",
    syncStartError: "Не удалось запустить синхронизацию. Проверьте подпись и настройки Znack.", syncCancelError: "Не удалось запросить остановку синхронизации.", restored: "Восстановлено GTIN: {count}", hidden: "Скрыто GTIN: {count}", restoreError: "Не удалось восстановить выбранные GTIN. Обновите список и повторите.", hideError: "Не удалось скрыть выбранные GTIN. Обновите список и повторите.",
    syncTitle: "Каталог участника Честный ЗНАК", syncDescription: "Авторизация и подпись выполняются в Java. Локальные пакеты сохраняются последовательно.", stopAria: "Остановить синхронизацию товаров Znack", stopping: "Остановка…", stop: "Остановить", syncAria: "Синхронизировать товары Znack", starting: "Запуск…", sync: "Синхронизировать",
    deletedTitle: "Скрытые GTIN", title: "Локальный каталог товаров", limits: "До 50 GTIN на странице · до 100 в одной операции", searchLabel: "Поиск товаров Znack", searchPlaceholder: "GTIN, название, категория, ТН ВЭД", searchAria: "Найти товар Znack", search: "Найти", categoriesAria: "Категории товаров Znack", categories: "Категории", noCategories: "Категорий нет",
    restoreAria: "Восстановить выбранные GTIN", hideAria: "Скрыть выбранные GTIN", processing: "Обработка…", restore: "Восстановить · {count}", hide: "Скрыть · {count}", refreshList: "Обновить список", loading: "Загрузка товаров Znack", loadError: "Не удалось загрузить каталог Znack", retry: "Повторить",
    deletedEmpty: "Скрытых GTIN нет", empty: "Локальный каталог Znack пока пуст", deletedEmptyHint: "Скрытые товары появятся здесь.", emptyHint: "Проверьте сертификат и запустите синхронизацию каталога.",
    columns: { product: "Товар", classification: "Классификация", readiness: "Готовность", kiz: "КИЗ" }, customsCode: "ТН ВЭД", unnamed: "Без названия", uncategorized: "Без категории", selectAria: "Выбрать GTIN {gtin}", buyAria: "Купить КИЗ для {gtin}", buy: "Купить",
    previousAria: "Предыдущая страница товаров Znack", previous: "Назад", page: "Страница {page}", nextAria: "Следующая страница товаров Znack", next: "Вперёд",
    readiness: { mark: "Маркировка", turn: "Оборот", markReady: "Маркировка готова", turnReady: "Оборот готов", markNotReady: "Маркировка не готова", turnNotReady: "Оборот не готов", noData: "{label}: нет данных" },
  },
  purchase: defaultPurchaseDialogCopy,
} as const;

type DeepString<T> = { [K in keyof T]: T[K] extends string ? string : DeepString<T[K]> };
export type ZnackCopy = DeepString<typeof ru>;

const en: ZnackCopy = {
  header: { aria: "Znack Automation", title: "Secure Znack workspace", description: "CryptoPro, catalog synchronization, and the local GTIN lifecycle without exposing secrets to the WebView.", badge: "Secure Java bridge" },
  tabs: { aria: "Znack sections", settings: "Settings", products: "Products", deleted: "Hidden", purchases: "Purchases", logs: "Log" },
  settings: { loading: "Loading Znack settings", loadError: "Could not load Znack settings", retryLoad: "Retry loading settings", saved: "Znack settings saved", saveError: "Could not save the settings. Load the current data and try again.", reloadCurrent: "Load current data", certificatesError: "Could not find CryptoPro certificates. Check the installation and try again.", certificateSaved: "Certificate verified and saved", certificateTestError: "Certificate verification failed. Find the certificates again and retry.", omsConnection: "OMS connection", defaultDocument: "Default document", documentNumber: "Document number", documentDate: "Document date", datePlaceholder: "dd.mm.yyyy", autoIntroduction: "Automatic introduction", autoIntroductionHint: "Start only when the documents and GTIN metadata are ready.", invalid: "Fill in the OMS fields and both document fields, or leave both document fields empty.", saving: "Saving…", save: "Save Znack settings", signature: { verifiedTitle: "Signature verified", verifiedDetail: "The configuration is ready for protected operations.", expiredTitle: "Certificate expired", expiredDetail: "Choose and verify a valid certificate.", notVerifiedTitle: "Signature not verified", notVerifiedDetail: "Find a CryptoPro certificate and verify the signature.", unconfiguredTitle: "Certificate not configured", unconfiguredDetail: "Discovery is local and the selector stays in Java." }, validUntil: "Valid until {date}", discoverAria: "Find CryptoPro certificates", discovering: "Searching…", discover: "Find certificates", saveFirst: "Save the settings changes first.", discoveryFailed: "Certificate discovery failed.", none: "No available certificates found.", inn: "TIN", expired: "Certificate expired", noPrivateKey: "Private key unavailable", ready: "Ready to verify", testAria: "Verify the selected certificate", testing: "Waiting for CryptoPro…", test: "Verify certificate", privacy: "Certificate selectors, thumbprints, executable paths, and metadata never enter the WebView." },
  products: { synced: "Products synchronized: {count}", syncCancelled: "Synchronization stopped. Local batches already saved were preserved.", syncRetryable: "Synchronization did not finish. Check the connection and try again.", syncRejected: "Synchronization was rejected. Check the certificate and Znack settings.", syncStatusError: "Could not load the Znack synchronization status.", syncStartError: "Could not start synchronization. Check the signature and Znack settings.", syncCancelError: "Could not request synchronization cancellation.", restored: "GTINs restored: {count}", hidden: "GTINs hidden: {count}", restoreError: "Could not restore the selected GTINs. Refresh the list and try again.", hideError: "Could not hide the selected GTINs. Refresh the list and try again.", syncTitle: "Chestny ZNAK participant catalog", syncDescription: "Authorization and signing run in Java. Local batches are stored sequentially.", stopAria: "Stop Znack product synchronization", stopping: "Stopping…", stop: "Stop", syncAria: "Synchronize Znack products", starting: "Starting…", sync: "Synchronize", deletedTitle: "Hidden GTINs", title: "Local product catalog", limits: "Up to 50 GTINs per page · up to 100 per operation", searchLabel: "Search Znack products", searchPlaceholder: "GTIN, name, category, or HS code", searchAria: "Search Znack products", search: "Search", categoriesAria: "Znack product categories", categories: "Categories", noCategories: "No categories", restoreAria: "Restore selected GTINs", hideAria: "Hide selected GTINs", processing: "Working…", restore: "Restore · {count}", hide: "Hide · {count}", refreshList: "Refresh list", loading: "Loading Znack products", loadError: "Could not load the Znack catalog", retry: "Retry", deletedEmpty: "No hidden GTINs", empty: "The local Znack catalog is empty", deletedEmptyHint: "Hidden products will appear here.", emptyHint: "Verify the certificate and start catalog synchronization.", columns: { product: "Product", classification: "Classification", readiness: "Readiness", kiz: "KIZ" }, customsCode: "HS code", unnamed: "Unnamed product", uncategorized: "Uncategorized", selectAria: "Select GTIN {gtin}", buyAria: "Buy KIZ for {gtin}", buy: "Buy", previousAria: "Previous Znack product page", previous: "Back", page: "Page {page}", nextAria: "Next Znack product page", next: "Next", readiness: { mark: "Marking", turn: "Introduction", markReady: "Marking ready", turnReady: "Introduction ready", markNotReady: "Marking not ready", turnNotReady: "Introduction not ready", noData: "{label}: no data" } },
  purchase: { invalidQuantity: "Enter a whole quantity from 1 to 10,000.", prepareError: "Could not prepare the purchase. Refresh the data and try again.", startError: "The purchase did not start. Check the order state before retrying.", confirmTitle: "Confirm KIZ purchase", prepareTitle: "Prepare KIZ purchase", unnamedProduct: "Unnamed product", close: "Close KIZ purchase", quantity: "Quantity", autoIntroductionTitle: "Automatic introduction is enabled", autoIntroductionDescription: "After downloading codes, WCode submits a document only when its data and documents are ready.", localOnly: "Codes will be downloaded locally without automatic introduction.", quantityLabel: "KIZ quantity", certificateRequired: "Save the settings and verify the CryptoPro certificate.", paidWarning: "This purchase may create a paid Znack order. Its confirmation UUID is stored before the first network call to prevent duplicate charges.", cancel: "Cancel", confirmLabel: "Confirm KIZ purchase", starting: "Starting…", confirm: "Confirm KIZ purchase", prepareLabel: "Prepare purchase", checking: "Checking…", prepare: "Prepare purchase" },
};

const vi: ZnackCopy = {
  header: { aria: "Znack Automation", title: "Không gian Znack bảo mật", description: "CryptoPro, đồng bộ danh mục và vòng đời GTIN cục bộ mà không đưa bí mật vào WebView.", badge: "Cầu nối Java bảo mật" },
  tabs: { aria: "Các mục Znack", settings: "Cài đặt", products: "Sản phẩm", deleted: "Đã ẩn", purchases: "Giao dịch", logs: "Nhật ký" },
  settings: { loading: "Đang tải cài đặt Znack", loadError: "Không thể tải cài đặt Znack", retryLoad: "Tải lại cài đặt", saved: "Đã lưu cài đặt Znack", saveError: "Không thể lưu cài đặt. Hãy tải dữ liệu hiện tại và thử lại.", reloadCurrent: "Tải dữ liệu hiện tại", certificatesError: "Không thể tìm chứng thư CryptoPro. Hãy kiểm tra cài đặt và thử lại.", certificateSaved: "Đã xác minh và lưu chứng thư", certificateTestError: "Không thể xác minh chứng thư. Hãy tìm lại chứng thư và thử lại.", omsConnection: "Kết nối OMS", defaultDocument: "Tài liệu mặc định", documentNumber: "Số tài liệu", documentDate: "Ngày tài liệu", datePlaceholder: "dd.mm.yyyy", autoIntroduction: "Tự động đưa vào lưu thông", autoIntroductionHint: "Chỉ bắt đầu khi tài liệu và metadata GTIN đã sẵn sàng.", invalid: "Điền các trường OMS và cả hai trường tài liệu, hoặc để trống cả hai trường tài liệu.", saving: "Đang lưu…", save: "Lưu cài đặt Znack", signature: { verifiedTitle: "Chữ ký đã xác minh", verifiedDetail: "Cấu hình đã sẵn sàng cho các thao tác được bảo vệ.", expiredTitle: "Chứng thư đã hết hạn", expiredDetail: "Hãy chọn và xác minh một chứng thư còn hiệu lực.", notVerifiedTitle: "Chữ ký chưa xác minh", notVerifiedDetail: "Hãy tìm chứng thư CryptoPro và xác minh chữ ký.", unconfiguredTitle: "Chưa cấu hình chứng thư", unconfiguredDetail: "Việc tìm kiếm diễn ra cục bộ và selector nằm trong Java." }, validUntil: "Có hiệu lực đến {date}", discoverAria: "Tìm chứng thư CryptoPro", discovering: "Đang tìm…", discover: "Tìm chứng thư", saveFirst: "Hãy lưu thay đổi cài đặt trước.", discoveryFailed: "Không tìm được chứng thư.", none: "Không tìm thấy chứng thư khả dụng.", inn: "MST", expired: "Chứng thư đã hết hạn", noPrivateKey: "Không có khóa riêng", ready: "Sẵn sàng xác minh", testAria: "Xác minh chứng thư đã chọn", testing: "Đang chờ CryptoPro…", test: "Xác minh chứng thư", privacy: "Selector, thumbprint, đường dẫn thực thi và metadata chứng thư không được đưa vào WebView." },
  products: { synced: "Số sản phẩm đã đồng bộ: {count}", syncCancelled: "Đã dừng đồng bộ. Các gói cục bộ đã lưu vẫn được giữ nguyên.", syncRetryable: "Đồng bộ chưa hoàn tất. Hãy kiểm tra kết nối và thử lại.", syncRejected: "Đồng bộ bị từ chối. Hãy kiểm tra chứng thư và cài đặt Znack.", syncStatusError: "Không thể lấy trạng thái đồng bộ Znack.", syncStartError: "Không thể bắt đầu đồng bộ. Hãy kiểm tra chữ ký và cài đặt Znack.", syncCancelError: "Không thể yêu cầu dừng đồng bộ.", restored: "GTIN đã khôi phục: {count}", hidden: "GTIN đã ẩn: {count}", restoreError: "Không thể khôi phục các GTIN đã chọn. Hãy cập nhật danh sách và thử lại.", hideError: "Không thể ẩn các GTIN đã chọn. Hãy cập nhật danh sách và thử lại.", syncTitle: "Danh mục thành viên Chestny ZNAK", syncDescription: "Việc xác thực và ký diễn ra trong Java. Các gói cục bộ được lưu tuần tự.", stopAria: "Dừng đồng bộ sản phẩm Znack", stopping: "Đang dừng…", stop: "Dừng", syncAria: "Đồng bộ sản phẩm Znack", starting: "Đang bắt đầu…", sync: "Đồng bộ", deletedTitle: "GTIN đã ẩn", title: "Danh mục sản phẩm cục bộ", limits: "Tối đa 50 GTIN mỗi trang · 100 mỗi thao tác", searchLabel: "Tìm sản phẩm Znack", searchPlaceholder: "GTIN, tên, danh mục hoặc mã HS", searchAria: "Tìm sản phẩm Znack", search: "Tìm", categoriesAria: "Danh mục sản phẩm Znack", categories: "Danh mục", noCategories: "Không có danh mục", restoreAria: "Khôi phục GTIN đã chọn", hideAria: "Ẩn GTIN đã chọn", processing: "Đang xử lý…", restore: "Khôi phục · {count}", hide: "Ẩn · {count}", refreshList: "Cập nhật danh sách", loading: "Đang tải sản phẩm Znack", loadError: "Không thể tải danh mục Znack", retry: "Thử lại", deletedEmpty: "Không có GTIN đã ẩn", empty: "Danh mục Znack cục bộ đang trống", deletedEmptyHint: "Sản phẩm đã ẩn sẽ xuất hiện tại đây.", emptyHint: "Hãy xác minh chứng thư và bắt đầu đồng bộ danh mục.", columns: { product: "Sản phẩm", classification: "Phân loại", readiness: "Mức sẵn sàng", kiz: "KIZ" }, customsCode: "Mã HS", unnamed: "Sản phẩm chưa có tên", uncategorized: "Chưa phân loại", selectAria: "Chọn GTIN {gtin}", buyAria: "Mua KIZ cho {gtin}", buy: "Mua", previousAria: "Trang sản phẩm Znack trước", previous: "Trước", page: "Trang {page}", nextAria: "Trang sản phẩm Znack sau", next: "Sau", readiness: { mark: "Đánh dấu", turn: "Lưu thông", markReady: "Đánh dấu sẵn sàng", turnReady: "Lưu thông sẵn sàng", markNotReady: "Đánh dấu chưa sẵn sàng", turnNotReady: "Lưu thông chưa sẵn sàng", noData: "{label}: không có dữ liệu" } },
  purchase: { invalidQuantity: "Nhập số nguyên từ 1 đến 10.000.", prepareError: "Không thể chuẩn bị giao dịch. Hãy cập nhật dữ liệu và thử lại.", startError: "Giao dịch chưa bắt đầu. Hãy kiểm tra trạng thái đơn trước khi thử lại.", confirmTitle: "Xác nhận mua KIZ", prepareTitle: "Chuẩn bị mua KIZ", unnamedProduct: "Sản phẩm chưa có tên", close: "Đóng giao dịch KIZ", quantity: "Số lượng", autoIntroductionTitle: "Đã bật tự động đưa vào lưu thông", autoIntroductionDescription: "Sau khi tải mã, WCode chỉ gửi chứng từ khi dữ liệu và tài liệu đã sẵn sàng.", localOnly: "Mã sẽ được tải cục bộ mà không tự động đưa vào lưu thông.", quantityLabel: "Số lượng KIZ", certificateRequired: "Hãy lưu cài đặt và xác minh chứng thư CryptoPro.", paidWarning: "Giao dịch này có thể tạo đơn Znack có tính phí. UUID xác nhận được lưu trước lệnh mạng đầu tiên để ngăn tính phí trùng.", cancel: "Hủy", confirmLabel: "Xác nhận mua KIZ", starting: "Đang bắt đầu…", confirm: "Xác nhận mua KIZ", prepareLabel: "Chuẩn bị giao dịch", checking: "Đang kiểm tra…", prepare: "Chuẩn bị giao dịch" },
};

const zh: ZnackCopy = {
  header: { aria: "Znack Automation", title: "Znack 安全工作区", description: "在不向 WebView 暴露秘密的情况下使用 CryptoPro、同步目录并管理本地 GTIN 生命周期。", badge: "安全 Java 桥接" },
  tabs: { aria: "Znack 分区", settings: "设置", products: "商品", deleted: "已隐藏", purchases: "购买", logs: "日志" },
  settings: { loading: "正在加载 Znack 设置", loadError: "无法加载 Znack 设置", retryLoad: "重试加载设置", saved: "Znack 设置已保存", saveError: "无法保存设置。请加载当前数据后重试。", reloadCurrent: "加载当前数据", certificatesError: "无法找到 CryptoPro 证书。请检查安装后重试。", certificateSaved: "证书已验证并保存", certificateTestError: "证书验证失败。请重新查找证书后重试。", omsConnection: "OMS 连接", defaultDocument: "默认文档", documentNumber: "文档编号", documentDate: "文档日期", datePlaceholder: "dd.mm.yyyy", autoIntroduction: "自动投入流通", autoIntroductionHint: "仅在文档和 GTIN 元数据就绪时启动。", invalid: "请填写 OMS 字段和两个文档字段，或将两个文档字段都留空。", saving: "正在保存…", save: "保存 Znack 设置", signature: { verifiedTitle: "签名已验证", verifiedDetail: "配置已可用于受保护的操作。", expiredTitle: "证书已过期", expiredDetail: "请选择并验证有效证书。", notVerifiedTitle: "签名未验证", notVerifiedDetail: "请查找 CryptoPro 证书并验证签名。", unconfiguredTitle: "证书未配置", unconfiguredDetail: "证书查找在本地进行，selector 保留在 Java 中。" }, validUntil: "有效期至 {date}", discoverAria: "查找 CryptoPro 证书", discovering: "正在查找…", discover: "查找证书", saveFirst: "请先保存设置更改。", discoveryFailed: "证书查找失败。", none: "未找到可用证书。", inn: "税号", expired: "证书已过期", noPrivateKey: "私钥不可用", ready: "可验证", testAria: "验证所选证书", testing: "正在等待 CryptoPro…", test: "验证证书", privacy: "证书 selector、指纹、可执行文件路径和元数据不会进入 WebView。" },
  products: { synced: "已同步商品：{count}", syncCancelled: "同步已停止，已保存的本地批次会保留。", syncRetryable: "同步未完成，请检查连接后重试。", syncRejected: "同步被拒绝，请检查证书和 Znack 设置。", syncStatusError: "无法获取 Znack 同步状态。", syncStartError: "无法启动同步，请检查签名和 Znack 设置。", syncCancelError: "无法请求停止同步。", restored: "已恢复 GTIN：{count}", hidden: "已隐藏 GTIN：{count}", restoreError: "无法恢复所选 GTIN，请刷新列表后重试。", hideError: "无法隐藏所选 GTIN，请刷新列表后重试。", syncTitle: "Chestny ZNAK 参与者目录", syncDescription: "授权和签名在 Java 中执行，本地批次按顺序保存。", stopAria: "停止 Znack 商品同步", stopping: "正在停止…", stop: "停止", syncAria: "同步 Znack 商品", starting: "正在启动…", sync: "同步", deletedTitle: "已隐藏的 GTIN", title: "本地商品目录", limits: "每页最多 50 个 GTIN · 每次操作最多 100 个", searchLabel: "搜索 Znack 商品", searchPlaceholder: "GTIN、名称、类别或 HS 编码", searchAria: "搜索 Znack 商品", search: "搜索", categoriesAria: "Znack 商品类别", categories: "类别", noCategories: "没有类别", restoreAria: "恢复所选 GTIN", hideAria: "隐藏所选 GTIN", processing: "正在处理…", restore: "恢复 · {count}", hide: "隐藏 · {count}", refreshList: "刷新列表", loading: "正在加载 Znack 商品", loadError: "无法加载 Znack 目录", retry: "重试", deletedEmpty: "没有已隐藏的 GTIN", empty: "本地 Znack 目录为空", deletedEmptyHint: "已隐藏商品会显示在这里。", emptyHint: "请验证证书并启动目录同步。", columns: { product: "商品", classification: "分类", readiness: "就绪状态", kiz: "KIZ" }, customsCode: "HS 编码", unnamed: "未命名商品", uncategorized: "未分类", selectAria: "选择 GTIN {gtin}", buyAria: "为 {gtin} 购买 KIZ", buy: "购买", previousAria: "上一页 Znack 商品", previous: "上一页", page: "第 {page} 页", nextAria: "下一页 Znack 商品", next: "下一页", readiness: { mark: "标记", turn: "流通", markReady: "标记已就绪", turnReady: "流通已就绪", markNotReady: "标记未就绪", turnNotReady: "流通未就绪", noData: "{label}：无数据" } },
  purchase: { invalidQuantity: "请输入 1 到 10,000 之间的整数。", prepareError: "无法准备购买。请刷新数据后重试。", startError: "购买未启动。重试前请检查订单状态。", confirmTitle: "确认购买 KIZ", prepareTitle: "准备购买 KIZ", unnamedProduct: "未命名商品", close: "关闭 KIZ 购买", quantity: "数量", autoIntroductionTitle: "已启用自动投入流通", autoIntroductionDescription: "下载码后，WCode 仅在数据和文档就绪时提交文档。", localOnly: "码将下载到本地，不会自动投入流通。", quantityLabel: "KIZ 数量", certificateRequired: "请保存设置并验证 CryptoPro 证书。", paidWarning: "此次购买可能创建付费 Znack 订单。确认 UUID 会在首次网络调用前保存，以防重复扣费。", cancel: "取消", confirmLabel: "确认购买 KIZ", starting: "正在启动…", confirm: "确认购买 KIZ", prepareLabel: "准备购买", checking: "正在检查…", prepare: "准备购买" },
};

const copies: Record<Language, ZnackCopy> = { ru, en, vi, zh };

export function getZnackCopy(language: Language): ZnackCopy {
  return copies[language];
}

export const defaultZnackCopy = ru;
